excludes = ["*.lock", ".envrc", ".gitignore"]

[formatter.markdownlint]
command = "markdownlint"
options = ["--fix"]
includes = ["*.md"]
priority = 0

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.css", "*.jsonc", "*.yaml"]
priority = 0

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
priority = 0
